use team02;

DROP TABLE IF EXISTS airport;
DROP TABLE IF EXISTS prediction;
DROP TABLE IF EXISTS trip;
DROP TABLE IF EXISTS Userliked;

DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS station;

DROP TABLE IF EXISTS landmark;
DROP TABLE IF EXISTS feedback;
DROP TABLE IF EXISTS city;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS continent;