INSERT INTO continent (continent_name, id) VALUES ('Europe', '3001');
INSERT INTO continent (continent_name, id) VALUES ('Asia', '3002');
INSERT INTO continent (continent_name, id) VALUES ('North America', '3003');
INSERT INTO continent (continent_name, id) VALUES ('Oceania', '3004');
INSERT INTO continent (continent_name, id) VALUES ('South America', '3005');
INSERT INTO continent (continent_name, id) VALUES ('Africa', '3006');
INSERT INTO continent (continent_name, id) VALUES ('Antarctica', '3007');


INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('UK', '826', 'GBR', 'GB', '3001', 'https://img.freepik.com/premium-vector/vector-image-of-the-british-flag-of-england-sign-of-the-kingdom-of-great-britain-lovely-london-badge_213497-1010.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Thailand', '764', 'THA', 'TH', '3002', 'https://img.freepik.com/free-vector/illustration-of-thailand-flag_53876-27145.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Indonesia', '360', 'IDN', 'ID', '3002', 'https://img.freepik.com/free-vector/illustration-of-indonesia-flag_53876-27131.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('USA', '840', 'USA', 'US', '3003', 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_the_United_States_%28DoS_ECA_Color_Standard%29.svg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Japan', '392', 'JPN', 'JP', '3002', 'https://img.freepik.com/premium-vector/japan-flag_855948-3.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('France', '250', 'FRA', 'FR', '3001', 'https://img.freepik.com/premium-vector/japan-flag_855948-3.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Australia', '36', 'AUS', 'AU', '3004', 'https://img.freepik.com/premium-vector/australia-flag-button-icon_147072-600.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Brazil', '76', 'BRA', 'BR', '3005', 'https://i.namu.wiki/i/zp21MgQRhFJiasIohLO-MnI7LB2jDRlN9pEpiMSMy_KAXJxPUJfPzlNU3G8JzpNnJ0_JOUHvQVA_4viZGYbn5A.svg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Netherlands', '528', 'NLD', 'NL', '3001', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/255px-Flag_of_the_Netherlands.svg.png');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('United Arab Emirates', '784', 'ARE', 'AE', '3002', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/255px-Flag_of_the_United_Arab_Emirates.svg.png');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Mexico', '484', 'MEX', 'MX', '3003', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/290px-Flag_of_Mexico.svg.png');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Spain', '724', 'ESP', 'ES', '3001', 'https://img.freepik.com/free-vector/illustration-of-spain-flag_53876-18168.jpg?size=626&ext=jpg&ga=GA1.1.1413502914.1697155200&semt=ais');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Germany', '276', 'DEU', 'DE', '3001', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_West_Germany%3B_Flag_of_Germany_%281990%E2%80%931996%29.svg/220px-Flag_of_West_Germany%3B_Flag_of_Germany_%281990%E2%80%931996%29.svg.png');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Morocco', '504', 'MAR', 'MA', '3006', 'https://www.infomorocco.net/uploads/9/4/9/2/9492999/moro-flag_orig.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Italy', '380', 'ITA', 'IT', '3001', 'https://img.freepik.com/free-vector/illustration-of-italy-flag_53876-27098.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Greece', '300', 'GRC', 'GR', '3001', 'https://img.freepik.com/premium-vector/flag-of-greece-vector-illustration_514344-273.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Egypt', '818', 'EGY', 'EG', '3006', 'https://img.freepik.com/free-vector/illustration-of-egypt-flag_53876-27140.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Canada', '124', 'CAN', 'CA', '3003', 'https://img.freepik.com/premium-vector/canada-flag-official-colors-and-proportion-correctly-national-canada-flag_721791-960.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('South Korea', '410', 'KOR', 'KR', '3002', 'https://img.freepik.com/premium-vector/vector-south-korea-flag_1001513-6.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('South Africa', '710', 'ZAF', 'ZA', '3006', 'https://img.freepik.com/premium-vector/national-flag-of-south-africa-with-official-colors_445068-1821.jpg');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('Cambodia', '116', 'KHM', 'KH', '3002','https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/510px-Flag_of_Cambodia.svg.png');
INSERT INTO country (name, iso_number, iso_code3, iso_code2, continent_id, flag) VALUES ('New Zealand', '554', 'NZL', 'NZ', '3004', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/1024px-Flag_of_New_Zealand.svg.png');
