INSERT INTO station (stationID, stationName, cityid) VALUES ('4001', 'Tokyo Train Station', '1005');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4002', 'Amsterdam Train Station', '1009');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4003', 'Barcelona Train Station', '1012');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4004', 'Edinburgh Train Station', '1016');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4005', 'Paris Plane Station', '1006');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4006', 'Bali Plane Station', '1003');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4007', 'London Train Station', '1001');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4008', 'Tokyo Plane Station', '1005');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4009', 'New York Bus Station', '1004');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4010', 'Sydney Plane Station', '1007');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4011', 'Rome Train Station', '1017');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4012', 'Bangkok Plane Station', '1018');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4013', 'Paris Train Station', '1006');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4014', 'Honolulu Plane Station', '1013');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4015', 'Phuket Train Station', '1002');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4016', 'Paris Car rental Station', '1006');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4017', 'Sydney Car rental Station', '1007');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4018', 'Rio de Janeiro Bus Station', '1008');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4019', 'Santorini Plane Station', '1019');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4020', 'Cairo Train Station', '1020');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4021', 'Cancun Plane Station', '1011');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4022', 'Barcelona Car rental Station', '1012');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4023', 'Vancouver Bus Station', '1021');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4024', 'Sydney Train Station', '1007');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4025', 'Rio de Janeiro Plane Station', '1008');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4026', 'Barcelona Plane Station', '1012');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4027', 'New York Plane Station', '1004');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4028', 'Bangkok Bus Station', '1018');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4029', 'Vancouver Train Station', '1021');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4030', 'Amsterdam Plane Station', '1009');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4031', 'Tokyo Bus Station', '1005');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4032', 'Rio de Janeiro Train Station', '1008');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4033', 'Seoul Subway Station', '1022');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4034', 'Los Angeles Car rental Station', '1023');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4035', 'Cape Town Car rental Station', '1024');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4036', 'Cape Town Car Station', '1024');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4037', 'Phuket Plane Station', '1002');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4038', 'Rome nan Station', '1017');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4039', 'New York Car rental Station', '1004');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4040', 'London Plane Station', '1001');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4041', 'Dubai Plane Station', '1010');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4042', 'Bangkok Train Station', '1018');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4043', 'Rome Plane Station', '1017');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4044', 'Bali Car rental Station', '1003');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4045', 'Seoul Train Station', '1022');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4046', 'Cape Town Plane Station', '1024');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4047', 'Rio de Janeiro Car rental Station', '1008');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4048', 'Santorini Ferry Station', '1019');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4049', 'Dubai Car rental Station', '1010');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4050', 'Phnom Penh Plane Station', '1025');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4051', 'Athens Plane Station', '1026');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4052', 'Paris Airplane Station', '1006');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4053', 'Sydney Airplane Station', '1007');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4054', 'New York Airplane Station', '1004');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4055', 'Rio de Janeiro Car Station', '1008');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4056', 'Vancouver Airplane Station', '1021');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4057', 'Barcelona Airplane Station', '1012');
INSERT INTO station (stationID, stationName, cityid) VALUES ('4058', 'Auckland Train Station', '1027');
