INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('BQH', 'EGKB', 'Biggin Hill Airport', '826', '1001');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('LGW', 'EGKK', 'Gatwick Airport', '826', '1001');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('LHR', 'EGLL', 'Heathrow Airport', '826', '1001');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('LCY', 'EGLC', 'London City Airport', '826', '1001');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('STN', 'EGSS', 'Stansted Airport', '826', '1001');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('HKT', 'VTSP', 'Phuket International Airport', '764', '1002');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('DPS', 'WADD', 'Ngurah Rai Airport', '360', '1003');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('JFK', 'KJFK', 'John F Kennedy International Airport', '840', '1004');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('LGA', 'KLGA', 'La Guardia International Airport', '840', '1004');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('IAG', 'KIAG', 'Niagara Falls International Airport', '840', '1004');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('NRT', 'RJAA', 'Narita Airport', '392', '1005');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('HND', 'RJTT', 'Tokyo International Airport', '392', '1005');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('CDG', 'LFPG', 'Charles De Gaulle Airport', '250', '1006');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('CHS', 'KCHS', 'Charleston International Airport', '840', '1006');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('ORY', 'LFPO', 'Orly Airport', '250', '1006');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('SYD', 'YSSY', 'Kingsford Smith Airport', '36', '1007');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('RIO', '', 'metropolitan area2', '76', '1008');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('GIG', 'SBGL', 'Rio de Janeiro International Airport', '76', '1008');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('SDU', 'SBRJ', 'Santos Dumont Regional Airport', '76', '1008');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('AMS', 'EHAM', 'Schiphol Airport', '528', '1009');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('DWC', 'OMDW', 'Al Maktoum International Airport', '784', '1010');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('DXB', 'OMDB', 'Dubai International Airport', '784', '1010');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('CUN', 'MMUN', 'Cancun International Airport', '484', '1011');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('BCN', 'LEBL', 'Barcelona International Airport', '724', '1012');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('HNL', 'PHNL', 'Honolulu International Airport', '840', '1013');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('BER', 'EDDB', 'Berlin Brandenburg Airport', '276', '1014');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('SXF', 'EDDB', 'Schoenefeld International Airport', '276', '1014');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('TXL', 'EDDT', 'Tegel International Airport', '276', '1014');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('RAK', 'GMMX', 'Menara Airport', '504', '1015');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('EDI', 'EGPH', 'Edinburgh Airport', '826', '1016');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('CIA', 'LIRA', 'Ciampino Airport', '380', '1017');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('CVG', 'KCVG', 'Cincinnati/Northern Kentucky International Airport', '840', '1017');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('DMK', 'VTBD', 'Don Mueang International', '764', '1018');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('BKK', 'VTBS', 'Suvarnabhumi International Airport', '764', '1018');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('JTR', 'LGSR', 'Santorini National Airport', '300', '1019');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('CAI', 'HECA', 'Cairo International Airport', '818', '1020');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('YVR', 'CYVR', 'Vancouver International Airport', '124', '1021');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('GMP', 'RKSS', 'Gimpo International Airport', '410', '1022');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('BTR', 'KBTR', 'Baton Rouge Metropolitan Airport', '840', '1023');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('LFT', 'KLFT', 'Lafayette Regional Airport', '840', '1023');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('MSY', 'KMSY', 'Louis Armstrong International Airport', '840', '1023');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('MLU', 'KMLU', 'Malad City Airport', '840', '1023');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('SHV', 'KSHV', 'Shreveport Regional Airport', '840', '1023');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('CPT', 'FACT', 'Cape Town International Airport', '710', '1024');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('PNH', 'VDPP', 'Pochentong Airport', '116', '1025');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('ATH', 'LGAV', 'Eleftherios Venizelos International Airport', '300', '1026');
INSERT INTO airport (IATA_code, ICAO_code, airport_name, country_id, city_id) VALUES ('AKL', 'NZAA', 'Auckland International Airport', '554', '1027');
